services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8010:8010"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8010
    ports:
      - "3000:3000"
    depends_on:
      - backend
